name: deploy-hotel
on:
  push:
    branches:
      - main
    paths:
      - 'hotel/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd hotel && docker build -t dimejifash45/hotel .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push dimejifash45/hotel
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save nasddatax
      - run: kubectl rollout restart deployment hotel-depl
      
      

      

      
      
      
      
      
